/* Setting up TEST DB */
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

CREATE TABLE IF NOT EXISTS parking (
    PARKING_NUMBER INT PRIMARY KEY,
    AVAILABLE BOOL NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PARKING_NUMBER INT NOT NULL,
    VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
    PRICE DOUBLE,
    IN_TIME DATETIME NOT NULL,
    OUT_TIME DATETIME,
    FOREIGN KEY (PARKING_NUMBER) REFERENCES parking (PARKING_NUMBER)
);

INSERT IGNORE INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (1, TRUE, 'CAR');
INSERT IGNORE INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (2, TRUE, 'CAR');
INSERT IGNORE INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (3, TRUE, 'CAR');
INSERT IGNORE INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (4, TRUE, 'BIKE');
INSERT IGNORE INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (5, TRUE, 'BIKE');

COMMIT;


