/* Setting up PROD DB */
DROP DATABASE IF EXISTS prod;
CREATE DATABASE prod;
USE prod;

CREATE TABLE IF NOT EXISTS parking (
    PARKING_NUMBER INT PRIMARY KEY,
    AVAILABLE BOOL NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS ticket;
CREATE TABLE ticket (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PARKING_NUMBER INT NOT NULL,
    VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
    PRICE DOUBLE,
    IN_TIME DATETIME NOT NULL,
    OUT_TIME DATETIME,
    FOREIGN KEY (PARKING_NUMBER) REFERENCES parking (PARKING_NUMBER)
);

INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (1, TRUE, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (2, TRUE, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (3, TRUE, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (4, TRUE, 'BIKE');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (5, TRUE, 'BIKE');

COMMIT;
/* Setting up TEST DB */
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

CREATE TABLE IF NOT EXISTS parking (
    PARKING_NUMBER INT PRIMARY KEY,
    AVAILABLE BOOL NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS ticket;
CREATE TABLE ticket (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PARKING_NUMBER INT NOT NULL,
    VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
    PRICE DOUBLE,
    IN_TIME DATETIME NOT NULL,
    OUT_TIME DATETIME,
    FOREIGN KEY (PARKING_NUMBER) REFERENCES parking (PARKING_NUMBER)
);

INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (1, TRUE, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (2, TRUE, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (3, TRUE, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (4, TRUE, 'BIKE');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (5, TRUE, 'BIKE');

INSERT INTO ticket (PARKING_NUMBER, VEHICLE_REG_NUMBER, PRICE, IN_TIME, OUT_TIME) 
VALUES (1, 'ABCDEF', 1.5, '2025-02-26 01:00:00', '2025-02-26 02:00:00');

COMMIT;
